// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpI_l6jgWrAbGyYWrJkDCPTIbUoXghmOU',
    appId: '1:34441273632:web:14a87aaec1ddacbb76b745',
    messagingSenderId: '34441273632',
    projectId: 'flutter-d2e96',
    authDomain: 'flutter-d2e96.firebaseapp.com',
    storageBucket: 'flutter-d2e96.appspot.com',
    measurementId: 'G-07TL016LS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBofcQrDWaDwuIahcBe52yFZEpqBr45RnU',
    appId: '1:34441273632:android:5e94647de6708e8076b745',
    messagingSenderId: '34441273632',
    projectId: 'flutter-d2e96',
    storageBucket: 'flutter-d2e96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6cKjNnmag6MwrmPlE2S90RrJqzkKQ9FQ',
    appId: '1:34441273632:ios:91b834cf537da2c276b745',
    messagingSenderId: '34441273632',
    projectId: 'flutter-d2e96',
    storageBucket: 'flutter-d2e96.appspot.com',
    iosClientId: '34441273632-s4mqs37jeve7jtlqtdchgeqfd34b9md2.apps.googleusercontent.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6cKjNnmag6MwrmPlE2S90RrJqzkKQ9FQ',
    appId: '1:34441273632:ios:91b834cf537da2c276b745',
    messagingSenderId: '34441273632',
    projectId: 'flutter-d2e96',
    storageBucket: 'flutter-d2e96.appspot.com',
    iosClientId: '34441273632-s4mqs37jeve7jtlqtdchgeqfd34b9md2.apps.googleusercontent.com',
    iosBundleId: 'com.example.learning',
  );
}
